// Generated by scripts/sync-input-protocol.py; edit keys.json.
pub const KEYS: &[KeyEntry] = &[
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 4,
        },
        token: "a",
        aliases: &[],
        code: Some("KeyA"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 5,
        },
        token: "b",
        aliases: &[],
        code: Some("KeyB"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 6,
        },
        token: "c",
        aliases: &[],
        code: Some("KeyC"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 7,
        },
        token: "d",
        aliases: &[],
        code: Some("KeyD"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 8,
        },
        token: "e",
        aliases: &[],
        code: Some("KeyE"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 9,
        },
        token: "f",
        aliases: &[],
        code: Some("KeyF"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 10,
        },
        token: "g",
        aliases: &[],
        code: Some("KeyG"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 11,
        },
        token: "h",
        aliases: &[],
        code: Some("KeyH"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 12,
        },
        token: "i",
        aliases: &[],
        code: Some("KeyI"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 13,
        },
        token: "j",
        aliases: &[],
        code: Some("KeyJ"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 14,
        },
        token: "k",
        aliases: &[],
        code: Some("KeyK"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 15,
        },
        token: "l",
        aliases: &[],
        code: Some("KeyL"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 16,
        },
        token: "m",
        aliases: &[],
        code: Some("KeyM"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 17,
        },
        token: "n",
        aliases: &[],
        code: Some("KeyN"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 18,
        },
        token: "o",
        aliases: &[],
        code: Some("KeyO"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 19,
        },
        token: "p",
        aliases: &[],
        code: Some("KeyP"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 20,
        },
        token: "q",
        aliases: &[],
        code: Some("KeyQ"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 21,
        },
        token: "r",
        aliases: &[],
        code: Some("KeyR"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 22,
        },
        token: "s",
        aliases: &[],
        code: Some("KeyS"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 23,
        },
        token: "t",
        aliases: &[],
        code: Some("KeyT"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 24,
        },
        token: "u",
        aliases: &[],
        code: Some("KeyU"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 25,
        },
        token: "v",
        aliases: &[],
        code: Some("KeyV"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 26,
        },
        token: "w",
        aliases: &[],
        code: Some("KeyW"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 27,
        },
        token: "x",
        aliases: &[],
        code: Some("KeyX"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 28,
        },
        token: "y",
        aliases: &[],
        code: Some("KeyY"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 29,
        },
        token: "z",
        aliases: &[],
        code: Some("KeyZ"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 30,
        },
        token: "1",
        aliases: &[],
        code: Some("Digit1"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 31,
        },
        token: "2",
        aliases: &[],
        code: Some("Digit2"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 32,
        },
        token: "3",
        aliases: &[],
        code: Some("Digit3"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 33,
        },
        token: "4",
        aliases: &[],
        code: Some("Digit4"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 34,
        },
        token: "5",
        aliases: &[],
        code: Some("Digit5"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 35,
        },
        token: "6",
        aliases: &[],
        code: Some("Digit6"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 36,
        },
        token: "7",
        aliases: &[],
        code: Some("Digit7"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 37,
        },
        token: "8",
        aliases: &[],
        code: Some("Digit8"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 38,
        },
        token: "9",
        aliases: &[],
        code: Some("Digit9"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 39,
        },
        token: "0",
        aliases: &[],
        code: Some("Digit0"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 58,
        },
        token: "f1",
        aliases: &[],
        code: Some("F1"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 59,
        },
        token: "f2",
        aliases: &[],
        code: Some("F2"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 60,
        },
        token: "f3",
        aliases: &[],
        code: Some("F3"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 61,
        },
        token: "f4",
        aliases: &[],
        code: Some("F4"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 62,
        },
        token: "f5",
        aliases: &[],
        code: Some("F5"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 63,
        },
        token: "f6",
        aliases: &[],
        code: Some("F6"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 64,
        },
        token: "f7",
        aliases: &[],
        code: Some("F7"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 65,
        },
        token: "f8",
        aliases: &[],
        code: Some("F8"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 66,
        },
        token: "f9",
        aliases: &[],
        code: Some("F9"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 67,
        },
        token: "f10",
        aliases: &[],
        code: Some("F10"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 68,
        },
        token: "f11",
        aliases: &[],
        code: Some("F11"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 69,
        },
        token: "f12",
        aliases: &[],
        code: Some("F12"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 104,
        },
        token: "f13",
        aliases: &[],
        code: Some("F13"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 105,
        },
        token: "f14",
        aliases: &[],
        code: Some("F14"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 106,
        },
        token: "f15",
        aliases: &[],
        code: Some("F15"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 107,
        },
        token: "f16",
        aliases: &[],
        code: Some("F16"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 108,
        },
        token: "f17",
        aliases: &[],
        code: Some("F17"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 109,
        },
        token: "f18",
        aliases: &[],
        code: Some("F18"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 110,
        },
        token: "f19",
        aliases: &[],
        code: Some("F19"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 111,
        },
        token: "f20",
        aliases: &[],
        code: Some("F20"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 112,
        },
        token: "f21",
        aliases: &[],
        code: Some("F21"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 113,
        },
        token: "f22",
        aliases: &[],
        code: Some("F22"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 114,
        },
        token: "f23",
        aliases: &[],
        code: Some("F23"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 115,
        },
        token: "f24",
        aliases: &[],
        code: Some("F24"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 80,
        },
        token: "left",
        aliases: &[],
        code: Some("ArrowLeft"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 79,
        },
        token: "right",
        aliases: &[],
        code: Some("ArrowRight"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 82,
        },
        token: "up",
        aliases: &[],
        code: Some("ArrowUp"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 81,
        },
        token: "down",
        aliases: &[],
        code: Some("ArrowDown"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 226,
        },
        token: "left_alt",
        aliases: &["alt"],
        code: Some("AltLeft"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 230,
        },
        token: "right_alt",
        aliases: &[],
        code: Some("AltRight"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 224,
        },
        token: "left_ctrl",
        aliases: &["ctrl", "control"],
        code: Some("ControlLeft"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 228,
        },
        token: "right_ctrl",
        aliases: &[],
        code: Some("ControlRight"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 225,
        },
        token: "left_shift",
        aliases: &["shift"],
        code: Some("ShiftLeft"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 229,
        },
        token: "right_shift",
        aliases: &[],
        code: Some("ShiftRight"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 227,
        },
        token: "left_gui",
        aliases: &["win", "gui"],
        code: Some("MetaLeft"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 231,
        },
        token: "right_gui",
        aliases: &[],
        code: Some("MetaRight"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 40,
        },
        token: "enter",
        aliases: &["return"],
        code: Some("Enter"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 41,
        },
        token: "esc",
        aliases: &["escape"],
        code: Some("Escape"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 42,
        },
        token: "backspace",
        aliases: &[],
        code: Some("Backspace"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 43,
        },
        token: "tab",
        aliases: &[],
        code: Some("Tab"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 44,
        },
        token: "space",
        aliases: &[],
        code: Some("Space"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 57,
        },
        token: "caps_lock",
        aliases: &["capslock"],
        code: Some("CapsLock"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 70,
        },
        token: "print_screen",
        aliases: &["printscreen"],
        code: Some("PrintScreen"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 71,
        },
        token: "scroll_lock",
        aliases: &["scrolllock"],
        code: Some("ScrollLock"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 72,
        },
        token: "pause",
        aliases: &[],
        code: Some("Pause"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 73,
        },
        token: "insert",
        aliases: &[],
        code: Some("Insert"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 74,
        },
        token: "home",
        aliases: &[],
        code: Some("Home"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 75,
        },
        token: "page_up",
        aliases: &["pageup"],
        code: Some("PageUp"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 76,
        },
        token: "delete",
        aliases: &[],
        code: Some("Delete"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 77,
        },
        token: "end",
        aliases: &[],
        code: Some("End"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 78,
        },
        token: "page_down",
        aliases: &["pagedown"],
        code: Some("PageDown"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 101,
        },
        token: "menu",
        aliases: &["application"],
        code: Some("ContextMenu"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 45,
        },
        token: "minus",
        aliases: &[],
        code: Some("Minus"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 46,
        },
        token: "equal",
        aliases: &[],
        code: Some("Equal"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 47,
        },
        token: "left_bracket",
        aliases: &[],
        code: Some("BracketLeft"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 48,
        },
        token: "right_bracket",
        aliases: &[],
        code: Some("BracketRight"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 49,
        },
        token: "backslash",
        aliases: &[],
        code: Some("Backslash"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 51,
        },
        token: "semicolon",
        aliases: &[],
        code: Some("Semicolon"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 52,
        },
        token: "quote",
        aliases: &["apostrophe"],
        code: Some("Quote"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 53,
        },
        token: "grave",
        aliases: &["backtick"],
        code: Some("Backquote"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 54,
        },
        token: "comma",
        aliases: &[],
        code: Some("Comma"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 55,
        },
        token: "dot",
        aliases: &["period"],
        code: Some("Period"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 56,
        },
        token: "slash",
        aliases: &[],
        code: Some("Slash"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 83,
        },
        token: "num_lock",
        aliases: &["numlock"],
        code: Some("NumLock"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 84,
        },
        token: "kp_slash",
        aliases: &[],
        code: Some("NumpadDivide"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 85,
        },
        token: "kp_asterisk",
        aliases: &[],
        code: Some("NumpadMultiply"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 86,
        },
        token: "kp_minus",
        aliases: &[],
        code: Some("NumpadSubtract"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 87,
        },
        token: "kp_plus",
        aliases: &[],
        code: Some("NumpadAdd"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 88,
        },
        token: "kp_enter",
        aliases: &[],
        code: Some("NumpadEnter"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 89,
        },
        token: "kp_1",
        aliases: &[],
        code: Some("Numpad1"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 90,
        },
        token: "kp_2",
        aliases: &[],
        code: Some("Numpad2"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 91,
        },
        token: "kp_3",
        aliases: &[],
        code: Some("Numpad3"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 92,
        },
        token: "kp_4",
        aliases: &[],
        code: Some("Numpad4"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 93,
        },
        token: "kp_5",
        aliases: &[],
        code: Some("Numpad5"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 94,
        },
        token: "kp_6",
        aliases: &[],
        code: Some("Numpad6"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 95,
        },
        token: "kp_7",
        aliases: &[],
        code: Some("Numpad7"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 96,
        },
        token: "kp_8",
        aliases: &[],
        code: Some("Numpad8"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 97,
        },
        token: "kp_9",
        aliases: &[],
        code: Some("Numpad9"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 98,
        },
        token: "kp_0",
        aliases: &[],
        code: Some("Numpad0"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 99,
        },
        token: "kp_dot",
        aliases: &[],
        code: Some("NumpadDecimal"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 100,
        },
        token: "intl_backslash",
        aliases: &[],
        code: Some("IntlBackslash"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 135,
        },
        token: "intl_ro",
        aliases: &[],
        code: Some("IntlRo"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 137,
        },
        token: "intl_yen",
        aliases: &[],
        code: Some("IntlYen"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 136,
        },
        token: "kana_mode",
        aliases: &[],
        code: Some("KanaMode"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 138,
        },
        token: "convert",
        aliases: &[],
        code: Some("Convert"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 7,
            usage: 139,
        },
        token: "non_convert",
        aliases: &[],
        code: Some("NonConvert"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 12,
            usage: 226,
        },
        token: "volume_mute",
        aliases: &[],
        code: Some("AudioVolumeMute"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 12,
            usage: 233,
        },
        token: "volume_up",
        aliases: &[],
        code: Some("AudioVolumeUp"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 12,
            usage: 234,
        },
        token: "volume_down",
        aliases: &[],
        code: Some("AudioVolumeDown"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 12,
            usage: 205,
        },
        token: "media_play_pause",
        aliases: &[],
        code: Some("MediaPlayPause"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 12,
            usage: 181,
        },
        token: "media_next",
        aliases: &[],
        code: Some("MediaTrackNext"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 12,
            usage: 182,
        },
        token: "media_previous",
        aliases: &[],
        code: Some("MediaTrackPrevious"),
    },
    KeyEntry {
        id: KeyId {
            usage_page: 12,
            usage: 183,
        },
        token: "media_stop",
        aliases: &[],
        code: Some("MediaStop"),
    },
];
