#!/usr/bin/env python3
"""Generate portable key tables, or verify generated files and an optional peer copy."""
from pathlib import Path
import argparse, json, shutil, subprocess
parser=argparse.ArgumentParser()
parser.add_argument('--check',action='store_true')
parser.add_argument('--peer',type=Path)
parser.add_argument('--mscv-rust',type=Path)
parser.add_argument('--mscv-cpp',type=Path)
a=parser.parse_args()
root=Path(__file__).resolve().parents[1]; shared=root/'shared/input-protocol'
s=json.loads((shared/'keys.json').read_text()); rows=s['keys']
rust='// Generated by scripts/sync-input-protocol.py; edit keys.json.\n'
rust+='pub const KEYS: &[KeyEntry] = &[\n'
for r in rows:
    rust+=f'    KeyEntry {{ id: KeyId {{ usage_page: {r["page"]}, usage: {r["usage"]} }}, token: {json.dumps(r["token"])}, aliases: &'+json.dumps(r['aliases'])+', code: '+('Some('+json.dumps(r['code'])+')' if r['code'] else 'None')+' },\n'
rust+='];\n'
rust=subprocess.run(['rustfmt','--edition','2021'],input=rust,text=True,capture_output=True,check=True).stdout
cpp='// Generated from shared/input-protocol/keys.json.\n#pragma once\n#include <stdint.h>\nnamespace key_catalog {\n'
cpp+='constexpr uint16_t ConsumerUsages[] = {'+','.join(str(u) for u in s['consumer_usages'])+'};\n'
cpp+='inline bool keyboardSupported(uint16_t u) { switch(u) {\n'
cpp+=''.join('case '+str(r['usage'])+':\n' for r in rows if r['page']==7)
cpp+='return true; default: return false; } }\n}\n'
js='// Generated from keys.json; physical KeyboardEvent.code identities.\nconst HID_KEY_CODE_MAP = '+json.dumps({r['code']:{'p':r['page'],'u':r['usage']} for r in rows if r['code']},indent=2)+';\n'
js+='const HID_KEY_TOKEN_MAP = '+json.dumps({t:{'p':r['page'],'u':r['usage']} for r in rows for t in [r['token']]+r['aliases']},indent=2)+';\n'
vectors=json.loads((shared/'vectors.json').read_text())
cpp_vectors='// Golden wire vectors from shared/input-protocol/vectors.json.\n#pragma once\nconstexpr uint8_t WireVectors[][64] = {\n'+''.join('{'+','.join(str(b) for b in v['bytes'])+'},\n' for v in vectors)+'};\n'
outputs={shared/'src/keys_generated.rs':rust,shared/'keys_generated.js':js,shared/'keys_generated.h':cpp,root/'firmware/boards/rp2040/KeyCatalog.h':cpp,root/'firmware/boards/leonardo_avr/KeyCatalog.h':cpp,shared/'vectors_generated.h':cpp_vectors,root/'firmware/tests/ProtocolVectors.h':cpp_vectors}
# One canonical implementation; each standalone sketch receives normal .h/.cpp.
outputs[root/'firmware/common/input/KeyCatalog.h'] = cpp
for board in ['rp2040', 'leonardo_avr']:
    target = root/'firmware/boards'/board/'src/input'
    for source in (root/'firmware/common/input').glob('*'):
        if source.suffix in ('.h', '.cpp') and source.name != 'KeyCatalog.h':
            outputs[target/source.name] = '// Generated from firmware/common/input/'+source.name+'; do not edit this copy.\n'+source.read_text()
    outputs[target/'KeyCatalog.h'] = cpp
    for source in (root/'firmware/common/usb').glob('*'):
        if source.suffix in ('.h', '.cpp'):
            outputs[root/'firmware/boards'/board/'src/platform'/source.name] = '// Generated from firmware/common/usb/'+source.name+'; do not edit this copy.\n'+source.read_text()
# A retired generated translation unit must not silently remain in a sketch.
for board in ['rp2040', 'leonardo_avr']:
    for path in (root/'firmware/boards'/board/'src/input').glob('*'):
        if path.suffix in ('.h', '.cpp') and path not in outputs:
            if a.check: raise SystemExit('Unexpected generated source: '+str(path))
            if not path.read_text().startswith('// Generated from '):
                raise SystemExit('Refusing to remove manually authored input source: '+str(path))
            path.unlink()
for path,content in outputs.items():
    if a.check:
        if not path.exists() or path.read_text()!=content:raise SystemExit('Stale generated file: '+str(path))
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
if a.peer:
    target=a.peer/'crates/input-protocol'
    if a.check:
        for path in shared.rglob('*'):
            if path.is_file() and 'target' not in path.relative_to(shared).parts:
                other=target/path.relative_to(shared)
                if not other.exists() or other.read_bytes()!=path.read_bytes():raise SystemExit('Peer drift: '+str(other))
        if (a.peer/'web/key-usages.js').read_text()!=js:raise SystemExit('Browser key table drift')
    else:
        shutil.copytree(shared,target,dirs_exist_ok=True,ignore=shutil.ignore_patterns('target','Cargo.lock'))
        (a.peer/'web/key-usages.js').write_text(js)

if a.mscv_rust:
    target=a.mscv_rust/'crates/input-protocol'
    if a.check:
        for path in shared.rglob('*'):
            if path.is_file() and 'target' not in path.relative_to(shared).parts and path.name != 'Cargo.lock':
                other=target/path.relative_to(shared)
                if not other.exists() or other.read_bytes()!=path.read_bytes():raise SystemExit('MSCV Rust drift: '+str(other))
    else:
        shutil.copytree(shared,target,dirs_exist_ok=True,ignore=shutil.ignore_patterns('target','Cargo.lock'))
if a.mscv_cpp:
    tokens='// Generated from FirmwareManageTool_Rust/shared/input-protocol/keys.json.\n#pragma once\n#include <cstdint>\nnamespace hardware::v3 {\nstruct KeyToken { const char* token; std::uint16_t page, usage; };\ninline constexpr KeyToken KeyTokens[] = {\n'
    tokens+=''.join('    {'+json.dumps(token)+', '+str(row['page'])+', '+str(row['usage'])+'},\n' for row in rows for token in [row['token']]+row['aliases'])
    tokens+='};\n}\n'
    for path,content in {a.mscv_cpp/'include/hardware/input_protocol/key_tokens_generated.h':tokens,a.mscv_cpp/'include/hardware/input_protocol/vectors_generated.h':cpp_vectors.replace('#pragma once', '#pragma once\n#include <stdint.h>')}.items():
        if a.check:
            if not path.exists() or path.read_text()!=content:raise SystemExit('MSCV C++ drift: '+str(path))
        else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
